language: node_js

node_js:
  - 6
  - 8

matrix:
  fast_finish: true

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm --version

notifications:
  email: false
  slack:
    secure: DLIGNSCjyl3LuqI84eU/kKBtbe6NnPNMIFn+TkKHdnrnsE02Wm5JK0mEIYcDx2KeQrx2LJCjl1jbmart00UxvHgaq8vB7R5yNKKb/A8Cy2cWmWr/z+Jrc6qt9LtMzabyZI9vddrWSCVqYcnRM+aG3YIS1eL8AIznGmgLXfih9R4djyRooYSpqNmMYUfgFdRwlsuRmwQvqk5DkxZ12Br9xla5yMGS/mOJfN+nqZcHQFpeCguM3l7XU5c1BTCXfg9Fq43Nbb/zIsfwq/PjrZVDTPbo6y6wR+JRsO3mzovvcbqeOHnj2aEEF5Dh89gZo3ZZb0NlF74he9i0W6n7npmQobMWoB8Ghm+v83MbpECOo4vqqX09MvTw/E6AqmhJufnb19IvhVX4zW5cHrXm8r4URoPltylJiBpwtmoKVvdt31sdew7gwQzUMCL8B6SxWvxwIzPrlRyiEdUSeWXXOp+HUJ4etu+5re4icJlohpkYDrjksu3yAaW29XtqFj+y2QRwyGeHe/73lteH/CMQ8/ndnp5Pt9GKAV4QWqlTBfWqjHtCW+92jUzigJuU8G5Yc7m8EOktLV70Bv4kdcm7Y04BPn2mTQjnmp1HxLsuoEYPKolTn+5FDgBedzFW/x8v+Lg3yWHtrxoWnRMZaJyv4J67JMCuP7Kg96x75XbPU2tsbKk=

cache:
  directories:
    - "$HOME/.npm"
